# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rWxGZeizX0rM_gaG76uW6-s5tBLg5BrJ
"""

import pandas as pd
import os
if not os.path.exists('solutions.json'):
    print('remote loading')
    df=pd.read_json('https://zenodo.org/record/5526707/files/solutions.json?download=1')
    df.to_json('solutions.json',orient='records')
else:
    print('local loading')
    df=pd.read_json('solutions.json')

print(df.shape)
print(df.columns)

def get_hidden_sector(l):
  ps=list(itertools.combinations_with_replacement(l,2))
  Ss=set([abs(sum(p)) for p in ps])

  paress={}
  cumplen=[]
  
  for s in Ss:
    tmp=[p for p in ps if abs(sum(p))==s]
    flatten=[item for sublist in tmp for item in sublist]

    set_flatten=set(flatten)

    if sorted(set_flatten, key=abs)==sorted(l, key=abs):
      paress['S']=s
      paress['Pares']=tmp
      #print(paress)
      cumplen=[paress]
  return cumplen


df['hidden']=df['solution'].apply(get_hidden_sector)

print('*'*20)
print(df.iloc[0].to_dict())

